(function(g){var window=this;'use strict';var U3=function(a){a.oa("cardstatechange",a.Fk()&&a.Ro()?1:0)},V3=function(a,b){var c=g.Za(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},xib=function(a){var b=g.Lr(a);
a=g.Or(a);return new g.Ar(b.x,b.y,a.width,a.height)},yib=function(a,b,c){var d=void 0===d?{}:d;
var e;return e=g.PC(a,b,function(){g.QC(e);c.apply(a,arguments)},d)},Y3=function(a){a=g.cb(a);
delete W3[a];g.id(W3)&&X3&&X3.stop()},Aib=function(){X3||(X3=new g.eu(function(){zib()},20));
var a=X3;a.isActive()||a.start()},zib=function(){var a=g.ib();
g.Tc(W3,function(b){Bib(b,a)});
g.id(W3)||Aib()},Z3=function(a,b,c,d){g.Au.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.B=a;this.N=b;this.duration=c;this.G=d;this.coords=[];this.progress=this.K=0;this.D=null},Bib=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.K=1E3/(b-a.D);a.D=b;Cib(a,a.progress);1==a.progress?(a.j=0,Y3(a),a.onFinish(),a.lr()):a.isPlaying()&&a.UK()},Cib=function(a,b){"function"===typeof a.G&&(b=a.G(b));
a.coords=Array(a.B.length);for(var c=0;c<a.B.length;c++)a.coords[c]=(a.N[c]-a.B[c])*b+a.B[c]},Dib=function(a,b){g.xb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.K;this.state=b.j},$3=function(a,b,c,d,e){Z3.call(this,b,c,d,e);
this.element=a},Eib=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
$3.call(this,a,b,c,d,e)},Fib=function(a){return Math.pow(a,3)},Gib=function(a){return 3*a*a-2*a*a*a},Hib=function(a){g.J.call(this);
this.B=a||window;this.j=[]},a4=function(a){return a.baseUrl||null},b4=function(a,b){return g.Ds(g.eq(a,b),function(c){return!!c})},Iib=function(a,b,c){function d(pa){var ma=pa.hovercardButton;
if(!ma)return null;ma=ma.subscribeButtonRenderer;if(!ma)return null;var Ca=f(ma.unsubscribedButtonText),Z=f(ma.subscribedButtonText);if(ma.subscribed){var Ea=f(ma.subscriberCountWithUnsubscribeText);var aa=f(ma.subscriberCountText)}else Ea=f(ma.subscriberCountText),aa=f(ma.subscriberCountWithSubscribeText);var Na=null;if(pa.signinEndpoint){Na=V3(pa,"signinEndpoint","webNavigationEndpointData","url");if(!Na){var y,T;Na=null==(T=g.S(null==(y=ma.signInEndpoint)?void 0:y.commandMetadata,g.L2))?void 0:
T.url}if(!Na)return null}return Ca&&(Z||Na)?{subscribed:ma.subscribed,subscribeText:Ca,subscribeCount:Ea,unsubscribeText:Z,unsubscribeCount:aa,enabled:ma.enabled,signinUrl:Na,classic:pa.useClassicSubscribeButton}:null}
function e(pa){if(pa){var ma=[],Ca=pa.videoId;Ca&&ma.push("v="+Ca);(Ca=pa.playlistId)&&ma.push("list="+Ca);(pa=pa.startTimeSeconds)&&ma.push("t="+pa);return"/watch?"+ma.join("&")}}
function f(pa){if(!pa)return null;var ma=pa.simpleText;return ma?ma:pa.runs?g.eq(pa.runs,function(Ca){return Ca.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,t=null,v=null,x=!1,C=null,G=null,F=null,I=null,O=null,Q=null;if("VIDEO"===h)g.S(l,g.CG)?m=g.S(l,g.CG).url:(Q=g.S(l,g.pT),m=e(Q)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.S(l,g.CG)?m=g.S(l,g.CG).url:(Q=g.S(l,g.pT),m=e(Q)),n=!1,q=a,t=f(b.playlistLength);else if("CHANNEL"===
h){if(x=V3(l,"browseEndpoint","browseId"))v=x,m="/channel/"+v;n=!1;q="new";(x=!!b.isSubscribe)?C=d(b):G=f(b.subscribersText)}else"WEBSITE"===h?((F=V3(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(I=f(b.productPrice)),b.additionalFeesText&&(O=f(b.additionalFeesText)),(n=V3(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=V3(b,"title","accessibility","accessibilityData","label");var Y=b.endpoint?b.endpoint.clickTrackingParams:null,
ia="";if(b.metadata){var ta=f(b.metadata);ta&&(ia=ta)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ia,callToAction:f(b.callToAction),sV:b.image,iconUrl:F,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,HD:p,playlistLength:t,channelId:v,subscribeButton:C,subscribersText:G,isSubscribe:x,pu:m||null,r6:n,sessionData:Y?{itct:Y}:null,raa:q,jC:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:b4(b.impressionUrls||[],a4),e6:b4(b.hovercardShowUrls||[],a4),clickUrls:b4(l.loggingUrls||[],a4),visualElement:g.IF(b.trackingParams),productPrice:I,additionalFeesText:O,watchEndpoint:Q||null}},Jib=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:b4(a.impressionUrls||[],a4),elements:b4(a.elements||[],function(d,e){return Iib(b,d,e)})};
a.trackingParams&&(c.visualElement=g.IF(a.trackingParams));return c},Kib=function(a){g.xV.call(this,a);
this.C=this.endscreen=null;this.j={};this.G={};this.D=this.B=null;this.N=[];this.Y=!0;this.K=0;a=a.U();this.Z=g.gS(a)||g.iS(a);this.events=new g.TK(this);g.L(this,this.events);this.events.T(this.player,g.jK("creatorendscreen"),this.onCueRangeEnter);this.events.T(this.player,g.kK("creatorendscreen"),this.onCueRangeExit);this.events.T(this.player,"resize",this.Lb);this.events.T(window,"focus",this.Q9);this.load();var b=g.mf("STYLE");(g.Qe("HEAD")[0]||document.body).appendChild(b);g.ub(this,function(){g.rf(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},Lib=function(a){return a.player.getVideoData().Qd?"current":a.Z?"new":"current"},c4=function(a){return"creator-endscreen-editor"===a.player.U().playerStyle},Mib=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.C&&a.C.abort();c={method:"POST",onFinish:function(e){var f=a.C=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=Jib(f,Lib(a))));d4(a,f)},
urlParams:{v:c},withCredentials:!0};a.Z&&(c.urlParams.ptype="embedded");var d=b.Vx;d&&(c.postParams={ad_tracking:d});if(b=g.qRa(b))if(b=g.Gn(b),b=g.$d(b))a.C=g.gC(b,c)},d4=function(a,b,c){c=void 0===c?!0:c;
a.player.hf("creatorendscreen");a.B&&(a.B.dispose(),a.B=null,a.D.dispose(),a.D=null);for(var d=g.u(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.G={};0<a.N.length&&(a.N.forEach(function(l){l.dispose()}),a.N.length=0);
a.K=0;if((a.endscreen=b)&&b.elements){c&&Nib(a);c=[];d=new g.iK(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.U().B||(a.B=new g.U({I:"div",S:"ytp-ce-shadow"}),g.qU(a.player,a.B.element,4),a.D=new g.PG(a.B,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=Oib(a,e);if(f){a.j[e.id]=f;a.G[e.id]=e;g.qU(a.player,f.element,4);var h=new g.iK(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);Pib(a,f,e)}else g.OF(new g.fD("buildEndscreenElement null",
e))}a.player.tf(c);a.Lb()}},Nib=function(a){var b=g.JF(),c=g.KF();
c&&b&&a.endscreen.visualElement&&g.OB(g.UF)(void 0,c,b,a.endscreen.visualElement)},Oib=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={I:"div",Ma:["ytp-ce-element","ytp-ce-video"],W:{tabindex:"0","aria-label":b.jC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.pu),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-video-title","ytp-webkit-ellipsis"],W:{dir:g.Fu(b.title||"")},xa:b.title},{I:"div",S:b.HD?"ytp-ce-live-video-duration":"ytp-ce-video-duration",xa:b.videoDuration||
void 0}]}]};c=new g.U(a);break;case "PLAYLIST":a={I:"div",Ma:["ytp-ce-element","ytp-ce-playlist"],W:{tabindex:"0","aria-label":b.jC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-covering-image",W:e4(b)},{I:"div",S:"ytp-ce-covering-shadow-top"},{I:"a",S:"ytp-ce-covering-overlay",W:{href:f4(a,b.pu),tabindex:"-1"},V:[{I:"div",Ma:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],W:{dir:g.Fu(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-playlist-count",V:[{I:"div",S:"ytp-ce-playlist-icon"},
{I:"div",S:"ytp-ce-playlist-count-text",xa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={I:"div",Ma:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],W:{tabindex:"0","aria-label":b.jC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"a",Ma:["ytp-ce-channel-title","ytp-ce-link"],W:{href:f4(a,b.pu),target:"_blank",tabindex:"-1",dir:g.Fu(b.title||"")},xa:b.title},b.subscribeButton?{I:"div",S:"ytp-ce-subscribe-container",V:[{I:"div",S:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{I:"div",S:"ytp-ce-channel-subscribers-text",xa:b.subscribersText}:"",b.metadata?{I:"div",Ma:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
xa:b.metadata}:""]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)}]};c=new g.U(c);var d=g.Re(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.mu(d,"ytp-ce-subscribe-button");if(a.player.U().B){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.jW(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":a={I:"div",Ma:["ytp-ce-element","ytp-ce-website"],W:{tabindex:"0","aria-label":b.jC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",
S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-website-title",W:{dir:g.Fu(b.title||"")},xa:b.title},{I:"div",S:"ytp-ce-website-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-website-goto","ytp-ce-link"],W:{href:f4(a,b.pu),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-expanding-icon",W:Qib(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={I:"div",S:"ytp-ce-merchandise-price-container",
V:[{I:"div",S:"ytp-ce-merchandise-price",xa:b.productPrice}]},b.additionalFeesText&&c.V.push({I:"div",S:"ytp-ce-merchandise-additional-fees",xa:b.additionalFeesText})),a={I:"div",Ma:["ytp-ce-element","ytp-ce-merchandise"],W:{tabindex:"0","aria-label":b.jC||"","aria-hidden":"true"},V:[{I:"div",S:"ytp-ce-element-shadow"},{I:"div",S:"ytp-ce-expanding-overlay",V:[{I:"div",S:"ytp-ce-expanding-overlay-hider"},{I:"div",S:"ytp-ce-expanding-overlay-background"},{I:"div",S:"ytp-ce-expanding-overlay-content",
V:[{I:"div",S:"ytp-ce-expanding-overlay-body",V:[{I:"div",S:"ytp-ce-expanding-overlay-body-padding",V:[{I:"div",S:"ytp-ce-merchandise-title",W:{dir:g.Fu(b.title||"")},xa:b.title},c,{I:"div",S:"ytp-ce-merchandise-metadata",xa:b.metadata},{I:"a",Ma:["ytp-ce-merchandise-goto","ytp-ce-link"],W:{href:f4(a,b.pu),target:"_blank",tabindex:"-1"},xa:b.callToAction}]}]}]}]},{I:"div",S:"ytp-ce-expanding-image",W:e4(b)},{I:"div",S:"ytp-ce-merchandise-invideo-cta-container",V:[{I:"div",S:"ytp-ce-merchandise-invideo-cta",
xa:b.callToAction||void 0}]}]},c=new g.U(a)}b.isPlaceholder&&g.mu(c.element,"ytp-ce-placeholder");return c},e4=function(a){if(a.sV)var b=a.sV.thumbnails;
return Qib(b?b[b.length-1].url:null)},Qib=function(a){return a?{style:"background-image: url("+a+")"}:{}},Pib=function(a,b,c){function d(m){m&&(b.Sa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.T(m,"focus",f),b.T(m,"blur",h))}
function e(m){a.K+=m;0<a.K?(g.mu(b.element,"ytp-ce-force-expand"),g4(a,c.id,!0)):(g.ou(b.element,"ytp-ce-force-expand"),g.ou(b.element,"ytp-ce-element-hover"),g4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Sa("mouseenter",function(){Rib(a,b,c)});
b.Sa("mouseleave",function(){Sib(a,b,c)});
a.player.U().B||b.Sa("click",function(){g.mu(b.element,"ytp-ce-element-hover")});
b.Sa("click",function(m){Tib(a,c,m)});
b.Sa("keypress",function(m){Tib(a,c,m)});
b.Sa("focus",function(){Rib(a,b,c)});
b.Sa("blur",function(){Sib(a,b,c)});
b.Sa("touchstart",function(){Rib(a,b,c)});
var l=g.Ze("ytp-ce-expanding-overlay-hider",b.element);l&&b.T(l,"touchstart",function(m){m.stopPropagation();g.ou(b.element,"ytp-ce-element-hover");g.ou(b.element,"ytp-ce-force-expand")});
b.Sa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.Ze("ytp-sb-subscribe",b.element));d(g.Ze("ytp-sb-unsubscribe",b.element));b.Sa("focus",f);b.Sa("blur",h)},Tib=function(a,b,c){if(b.pu&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.lu(d,"ytp-ce-element");){g.lu(d,"subscribe-label")&&Uib(a,b);
if(g.lu(d,"ytp-ce-channel-subscribe"))return;d=g.sf(d)}if(!d||g.lu(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Sib(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.raa)Uib(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Gn(f4(a,b.pu)),g.oH(g.$d(c),void 0,b.sessionData);else{var e=g.sS(a.player.U())||a.player.getVideoData().Qd,f=function(){var h=f4(a,b.pu),l=b.sessionData,m=b.watchEndpoint,n=g.UB(h);e&&n&&(n.v||n.list)?a.player.xo(n.v,
l,n.list,!1,void 0,m||void 0):g.bwa(h,l)};
Uib(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},f4=function(a,b){a=a.player.U();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.zS(a)+b}else return"";return b},Rib=function(a,b,c){g.lu(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.mu(b.element,"ytp-ce-element-hover"):a.player.U().B?(new g.eu(function(){g.mu(b.element,"ytp-ce-element-hover")},200)).start():g.mu(b.element,"ytp-ce-element-hover"),h4(a,c.e6),g4(a,c.id,!0))},Sib=function(a,b,c){g.ou(b.element,"ytp-ce-element-hover");
g.ou(b.element,"ytp-ce-force-expand");g4(a,c.id,!1)},g4=function(a,b,c){a.B&&(c?a.D.show():a.D.hide());
for(var d=g.u(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.qu(a.j[e].element,"ytp-ce-element-shadow-show",c)},h4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||c4(a))c&&c();else{b=Vib(a,b);var e=0,f=!1,h=new g.eu(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.zE(b[a],d)}},Uib=function(a,b,c){h4(a,b.clickUrls,c);
(a=g.KF())&&b.r6&&g.aG(a,b.visualElement)},Vib=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Wib(b[d],c));return a},Wib=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Xib=function(a){return"string"===typeof a?a:""},i4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Yib=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},j4=function(a){return a.value?a.value:null},k4=function(a){if(!a)return null;
var b=g.Gn(Xib(a.value));b=g.$d(b);if(!b)return null;var c=i4(a.target,Zib,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Yib(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},$ib=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},cjb=function(a){if(!a)return null;
var b=i4(a.type,ajb),c=i4(a.trigger,bjb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=k4(a?a:null);return b?new $ib(b,c,a):null},djb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},ejb=function(a,b){return g.Bb(a.action,b)},fjb=function(a,b){this.context=a;
this.j=b},gjb=function(a){return a.customMessage?l4("div","iv-card-message",a.customMessage):""},m4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{I:"div",S:"iv-card-image",W:{style:a},V:c}},hjb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.u(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(l4("li","",c.value));return{I:"ul",S:"iv-card-meta-info",V:b}},l4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Fu(c);return{I:a,W:b,xa:c}},ijb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.tC&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.tC+");");c.dir=g.Fu(a.customMessage);var d=[{I:"span",xa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({I:"span",S:"iv-card-link-icon"}));return{I:"div",Ma:b,W:c,V:d}},n4=function(a,b,c,d){if(d){b=g.u(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.bj.click,5)}},jjb=function(a,b){this.merchant=a;
this.price=b},kjb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},ljb=function(a,b){return b?b:kjb(a)?"current":"new"},o4=function(a,b){g.J.call(this);
var c=this;this.element=a;this.context=b;this.wb=!1;this.Za=new Map;this.fb=new Map;this.context.J.addEventListener(g.jK("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.J.addEventListener(g.kK("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},p4=function(a,b,c,d,e,f,h){a.context.j.Sa(b,"click",function(l){a.VK(c,d,e,f||[],h||0,l)});
a.context.j.Sa(b,"touchstart",function(){a.wb=!1});
a.context.j.Sa(b,"touchmove",function(){a.wb=!0})},mjb=function(a){var b;
return(null==(b=g.S(a,g.CG))?0:b.url)?g.S(a,g.CG).url:(a=g.S(a,g.pT))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},q4=function(a,b,c){return{PW:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
e_:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
vK:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},njb=function(a,b,c){o4.call(this,b,c);
var d=this;this.J=a;this.eventId=null;this.Na=this.Ib=this.C=this.isInitialized=!1;this.cards=[];this.yb=this.Z=this.La=this.G=this.Va=this.j=null;this.ma=[];this.qa=this.N=this.og=this.Da=null;this.K=0;this.Ga=new g.eu(function(){},c.X.Ki?4E3:3E3);
g.L(this,this.Ga);this.jb=new g.eu(function(){});
g.L(this,this.jb);this.Aa=new fjb(c,function(e,f,h,l,m,n){p4(d,e,f,h,l,m,n)});
this.Y=new g.U({I:"div",S:"iv-drawer",W:{id:"iv-drawer"},V:[{I:"div",S:"iv-drawer-header",W:{"aria-role":"heading"},V:[{I:"span",S:"iv-drawer-header-text"},{I:"button",Ma:["iv-drawer-close-button","ytp-button"],W:{"aria-label":"Hide cards",tabindex:"0"}}]},{I:"div",S:"iv-drawer-content"}]});g.L(this,this.Y);this.D=this.Y.element;this.ib=new g.PG(this.Y,330);g.L(this,this.ib);this.Qb=g.Ze("iv-drawer-header-text",this.D);this.B=g.Ze("iv-drawer-content",this.D);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Ib&&r4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ib=d.C)&&s4(d)});
this.Ta=new g.TK(this);g.L(this,this.Ta);this.J.addEventListener("videodatachange",this.kt.bind(this))},ojb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){r4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){s4(a)});
var c=b.headerText;g.Df(a.Qb,c);a.Z&&a.Z.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Da=g.IF(b.trackingParams);a.N=g.IF(b.closeTrackingParams);a.og=g.IF(b.iconTrackingParams)},pjb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.K,d=a.J.U().experiments.ob("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.qG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,bj:{},So:null,Al:e.trackingParams?g.IF(e.trackingParams):null,og:f&&f.trackingParams?g.IF(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
tC:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};t4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"simple",teaserText:g.qG(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:u4(a,c,b,f),sponsored:!1,bj:q4(f,e,f.command),So:f.trackingParams?g.IF(f.trackingParams):null,Al:e.trackingParams?g.IF(e.trackingParams):null,og:l&&l.trackingParams?g.IF(l.trackingParams):null,imageUrl:v4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.qG(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,tC:null,title:f.title?g.qG(f.title):"",customMessage:f.callToAction?g.qG(f.callToAction):"",url:g.S(f.command,g.CG).url?k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(f.command,g.CG).url}):null,onClickCommand:null};t4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"collaborator",teaserText:g.qG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.endpoint),So:e.trackingParams?g.IF(e.trackingParams):null,Al:f.trackingParams?g.IF(f.trackingParams):null,og:l&&l.trackingParams?g.IF(l.trackingParams):null,channelId:g.S(e.endpoint,g.QU).browseId,customMessage:e.customText?g.qG(e.customText):null,cZ:v4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.qG(e.channelName):"",metaInfo:[e.subscriberCountText?g.qG(e.subscriberCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.S(e.endpoint,g.QU).canonicalBaseUrl?g.S(e.endpoint,g.QU).canonicalBaseUrl:"/channel/"+g.S(e.endpoint,g.QU).browseId}),onClickCommand:null};t4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"playlist",teaserText:g.qG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.action),So:e.trackingParams?g.IF(e.trackingParams):null,Al:f.trackingParams?g.IF(f.trackingParams):null,og:l&&l.trackingParams?g.IF(l.trackingParams):null,IF:v4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.qG(e.customMessage):null,playlistVideoCount:g.qG(e.playlistVideoCount),title:e.playlistTitle?g.qG(e.playlistTitle):"",metaInfo:[e.channelName?g.qG(e.channelName):
"",e.videoCountText?g.qG(e.videoCountText):""],url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mjb(e.action)}),onClickCommand:null};t4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.K,type:"video",teaserText:g.qG(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:u4(a,c,b,e),sponsored:!1,bj:q4(e,f,e.action),So:e.trackingParams?g.IF(e.trackingParams):null,Al:f.trackingParams?g.IF(f.trackingParams):null,og:l&&l.trackingParams?g.IF(l.trackingParams):null,IF:v4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.qG(e.lengthString):null,customMessage:e.customMessage?g.qG(e.customMessage):null,title:e.videoTitle?g.qG(e.videoTitle):"",metaInfo:[e.channelName?g.qG(e.channelName):
"",e.viewCountText?g.qG(e.viewCountText):""],isLiveNow:!!e.badge,url:k4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:mjb(e.action)}),onClickCommand:null};t4(a,b)}}}}}a.K++},v4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},u4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},rjb=function(a,b){if(b=qjb(a,b))b===a.j&&(a.j=null),a.J.removeCueRange(b.gg.id),g.rf(b.rM),g.Gb(a.cards,b),a.FG(),w4(a)},r4=function(a,b,c){if(!a.C){a.ib.show();
a.Va=new g.eu(function(){g.mu(a.context.J.getRootNode(),g.bZ.IV_DRAWER_OPEN)},0);
a.Va.start();a.Ta.T(a.B,"mousewheel",function(h){a.Ga.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.B.scrollTop+=h});
a.C=!0;var d=g.KF();d&&a.Da&&a.N&&g.ZF(d,[a.Da,a.N]);b={TRIGGER_TYPE:b};for(var e=g.u(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.zX||(f.zX=!0,sjb(a.context.logger,f.gg.bj.PW,b)),d&&g.ZF(d,[f.gg.So]);U3(a.J);c&&(a.G=new g.eu(function(){a.La=a.Z;a.yb.focus()},330),a.G.start())}},s4=function(a){a.C&&(a.ib.hide(),g.VC(a.Ta),g.ou(a.context.J.getRootNode(),g.bZ.IV_DRAWER_OPEN),a.C=!1,U3(a.J),a.G&&a.G.stop(),a.G=new g.eu(function(){a.La&&(a.La.focus(),a.La=null)},330),a.G.start())},ujb=function(a){g.nu(a.Db(),
[g.bZ.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.qU(a.J,a.D,5);tjb(a);a.Z=g.Ze("ytp-cards-button",a.J.getRootNode());a.yb=g.Ze("iv-drawer-close-button",a.D);a.isInitialized=!0},tjb=function(a){var b=g.Ze("iv-drawer-close-button",a.D);
a.context.j.Sa(b,"click",a.j4,a);a.context.j.Sa(a.B,"touchend",function(){a.Ga.start()});
a.context.j.Sa(a.B,"scroll",a.D4,a);a.context.B.subscribe("onHideControls",function(){a.Na=!0});
a.context.B.subscribe("onShowControls",function(){a.Na=!1});
a.context.B.subscribe("onVideoAreaChange",function(){a.Na=g.lu(a.J.getRootNode(),"ytp-autohide")});
a.ma.push(g.NE("iv-button-shown",a.E6,a));a.ma.push(g.NE("iv-button-hidden",a.D6,a));a.ma.push(g.NE("iv-teaser-shown",a.N0,a));a.ma.push(g.NE("iv-teaser-hidden",a.F6,a));a.ma.push(g.NE("iv-teaser-clicked",a.M0,a))},vjb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.S(b.onClickCommand,g.Ueb))?void 0:c.targetId)?(a.qa=b,!0):!1},wjb=function(a,b){a.qa=b;
var c=a.J.getVideoData();if(!c)return!1;c=g.QPa(c);if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.S(h[0],g.zYa))?void 0:d.timeRangeStartMillis)||0,a.qa=null,!0}return!1},t4=function(a,b){if(!vjb(a,b)||wjb(a,b)){var c=xjb(a,b);
if(c){var d={gg:b,rM:c.element,zX:!1};if(!b.onClickCommand){a.isInitialized||ujb(a);rjb(a,b.id);var e=yjb(a,d);g.Pb(a.cards,e,0,d);c.Ea(a.B,e);a.FG()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.C||(a.j=d,w4(a),zjb(a,d),r4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&Ajb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){Ajb(a,d)}),w4(a))}}},xjb=function(a,b){switch(b.type){case "simple":a=a.Aa;
var c=b.displayDomain?{I:"div",S:"iv-card-image-text",xa:b.displayDomain}:void 0;var d=ijb(b);c={I:"div",Ma:["iv-card"],V:[{I:"a",S:"iv-click-target",W:{href:b.url?j4(b.url)||"":""},V:[m4(b.imageUrl,c),{I:"div",S:"iv-card-content",V:[l4("h2",void 0,b.title),d]}]}]};c=new g.U(c);n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "collaborator":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-channel"],V:[{I:"a",Ma:["iv-click-target"],W:{href:j4(b.url)||"","data-ytid":b.channelId},V:[m4(b.cZ),{I:"div",
S:"iv-card-content",V:[gjb(b),{I:"h2",S:"iv-card-primary-link",xa:b.title},hjb(b)]}]}]};c=new g.U(c);n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "playlist":a=a.Aa;c={I:"div",Ma:["iv-card","iv-card-playlist"],V:[{I:"a",S:"iv-click-target",W:{href:j4(b.url)||""},V:[m4(b.IF,{I:"div",S:"iv-card-image-overlay",V:[{I:"span",S:"iv-card-playlist-video-count",xa:b.playlistVideoCount}]}),{I:"div",S:"iv-card-content",V:[gjb(b),l4("h2","iv-card-primary-link",b.title),hjb(b)]}]}]};c=new g.U(c);
n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "productListing":a=a.Aa;var e=0!=b.offers.length;c=["iv-card"];d="";var f=ijb(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({I:"div",S:"iv-card-offer-price",xa:f.price}),f.merchant&&e.push({I:"div",S:"iv-card-offer-merchant",xa:f.merchant}),f={I:"div",V:e});e=b.url?j4(b.url)||"":"";c={I:"div",Ma:c,W:{tabindex:"0"},V:[{I:"a",Ma:["iv-card-image","iv-click-target"],W:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{I:"div",S:"iv-card-content",V:[b.sponsored?{I:"div",S:"iv-card-sponsored",V:["Sponsored",{I:"div",S:"iv-ad-info-container",V:[{I:"div",S:"iv-ad-info",xa:"{{adInfo}}"},{I:"div",S:"iv-ad-info-icon-container",V:[{I:"div",S:"iv-ad-info-icon"},{I:"div",S:"iv-ad-info-callout"}]}]}]}:"",{I:"a",S:"iv-click-target",W:{href:e},V:[l4("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.mf("span");g.Df(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.le(d,"adInfo");n4(a,g.Ye("iv-click-target",c.element),b,b.url);b=c;break;case "video":a=a.Aa;d=b.videoDuration?{I:"span",S:"iv-card-video-duration",xa:b.videoDuration}:void 0;f=b.isLiveNow?{I:"span",Ma:["yt-badge","yt-badge-live"],xa:"LIVE NOW"}:null;e={I:"div",Ma:["iv-card","iv-card-video"],V:[{I:"a",S:"iv-click-target",W:{href:(null==(c=b.url)?void 0:j4(c))||""},V:[m4(b.IF,d),{I:"div",S:"iv-card-content",V:[gjb(b),l4("h2","iv-card-primary-link",b.title),hjb(b),f]}]}]};c=new g.U(e);n4(a,g.Ye("iv-click-target",
c.element),b,b.url);b=c;break;default:return null}return b},yjb=function(a,b){if(0===a.cards.length)return 0;
a=g.Cb(a.cards,function(c){return b.gg.startMs>c.gg.startMs||b.gg.startMs===c.gg.startMs&&b.gg.timestamp>=c.gg.timestamp?!0:!1});
return-1===a?0:a+1},Bjb=function(a){if(a.j)return"productListing"===a.j.gg.type;
if(a.J.L("enable_wn_infocards")){var b;return!(null==(b=a.cards)||!b.length)&&g.fq(a.cards,function(c){return"productListing"===c.gg.type})}return g.fq(a.cards,function(c){return"productListing"===c.gg.type})},w4=function(a){g.qu(a.J.getRootNode(),"ytp-cards-shopping-active",Bjb(a))},Ajb=function(a,b){if(!g.lu(a.J.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.KF(),d=a.j?a.j.gg.og:a.og;
c&&d&&g.$F(c,[d]);a.j=b;w4(a)}(c=a.isInitialized&&"none"==a.Db().style.display)||(c=a.context.J.getPlayerState(),d=0===c&&0===a.context.J.getCurrentTime(),c=!(1===c||3===c||d));c||b.gg.teaserDurationMs&&a.J.YA(!0,{teaserText:b.gg.teaserText,durationMs:b.gg.teaserDurationMs,onClickCommand:b.gg.onClickCommand});a.jb.isActive()||((!a.C||!a.Ga.isActive()&&a.Na)&&zjb(a,b),a.jb.start(910+b.gg.teaserDurationMs))}},zjb=function(a,b){a.Y.Gb?(b=new Z3([0,
a.B.scrollTop],[0,b.rM.offsetTop],600,Gib),a.context.C.Sa(b,"animate",function(c){a.B.scrollTop=c.y}),a.context.C.Sa(b,"finish",function(c){a.B.scrollTop=c.y}),b.play()):(g.mG(a.Y,!0),a.B.scrollTop=b.rM.offsetTop,g.mG(a.Y,!1))},x4=function(a){return a.j&&a.j.gg?a.j.gg:a.cards[0]&&a.cards[0].gg?a.cards[0].gg:null},qjb=function(a,b){return g.Bb(a.cards,function(c){return c.gg.id===b})},y4=function(a,b,c){o4.call(this,a,b);
this.annotation=c;this.isActive=!1},Cjb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},z4=function(a,b,c){y4.call(this,a,b,c);
this.B=null;this.N=!1;this.C=null;this.D=!1;this.j=this.K=this.G=null},Djb=function(a,b){var c=void 0===c?0:c;
var d=xib(b).width;g.Jr(b,d);c=new Eib(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,Fib);g.L(a,c);a.context.C.Sa(c,"begin",function(){g.Pr(b,!0)});
c.play()},Gjb=function(a,b){if(b.channel_name){var c=a.createElement({I:"div",
Ma:["iv-branding-context-name"],xa:b.channel_name}),d=a.createElement({I:"div",Ma:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.jW(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,a.context.J),a.j.Ea(d));var f=a.createElement({I:"div",Ma:["iv-branding-context-subscribe-caret"]}),h=a.createElement({I:"div",Ma:["branding-context-container-inner"]});h.appendChild(f);
h.appendChild(c);h.appendChild(d);g.Pr(h,!1);var l=a.createElement({I:"div",Ma:["branding-context-container-outer"]});l.appendChild(h);g.Dr(l,"right",b.image_width+"px");g.of(a.Db(),l);a.C=new g.eu(function(){Ejb(a,h,l)},500);
g.L(a,a.C);a.context.j.Sa(a.Db(),"mouseover",function(){Fjb(a,h,l,f,b.image_height)});
a.context.j.Sa(a.Db(),"mouseout",function(){a.C.start()})}},Fjb=function(a,b,c,d,e){a.C.stop();
if(!a.D){var f=g.Or(b);a.j||(b.style.width=g.Ir(f.width,!0),c.style.width=g.Ir(f.width,!0));g.Dr(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Dr(d,"right","1px");a.D=!0;g.Pr(b,!0);a.G=new g.eu(function(){g.mu(this.Db(),"iv-branding-active")},0,a);
a.G.start()}},Ejb=function(a,b,c){g.ou(a.Db(),"iv-branding-active");
a.K=new g.eu(function(){g.Pr(b,!1);a.j||(c.style.width=g.Ir(0,!0))},250);
a.K.start();a.D=!1},Hjb=function(a,b,c,d,e,f,h){this.j=a;
this.C=b;this.X=c;this.videoData=d;this.logger=e;this.J=f;this.B=h},Ijb=function(a,b,c){y4.call(this,a,b,c);
var d=this;this.Z=this.isCollapsed=this.Y=!1;this.K=5E3;this.B=this.C=this.j=this.D=null;this.N=this.createElement({I:"div",Ma:["iv-promo-contents"]});this.G=new g.eu(function(){d.j.setAttribute("aria-hidden","true");g.Pr(d.C,!1);g.Pr(d.B,!0)},700,this);
g.L(this,this.G)},Ljb=function(a,b,c){c.stopPropagation();
Jjb(a);Kjb(a,b);a.j.focus()},Mjb=function(a){a.isCollapsed||a.Z||a.D||(g.mu(a.Db(),"iv-promo-collapsed"),a.isCollapsed=!0,a.G.start())},Jjb=function(a){a.G.stop();
a.isCollapsed&&(g.pu(a.Db(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.Pr(a.B,!1),g.Pr(a.C,!0))},Kjb=function(a,b){a.D||(a.D=g.fg(function(){Njb(this);
Mjb(this)},b,a))},Njb=function(a){a.D&&(g.Sa.clearTimeout(a.D),a.D=null)},Ojb=function(a){this.J=a},sjb=function(a,b,c){b&&(c?A4(a,b.map(function(d){return g.Ut(d,c)})):A4(a,b))},A4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.u(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.zE(m,f);d&&(e++,0!==d&&a.J.sendVideoStatsEngageEvent(d,f))},Pjb=function(a){g.xV.call(this,a);
var b=this;this.Y=this.N=!1;this.loadNumber=0;this.K={};this.logger=new Ojb(this.player);this.D=new g.TK(this);this.G=this.ox=null;this.events=new g.TK(this);this.uh=this.Z=this.j=null;this.ma=[];g.L(this,this.D);this.D.T(this.player,"onVideoAreaChange",function(){b.oa("onVideoAreaChange")});
this.D.T(this.player,"onHideControls",function(){b.oa("onHideControls")});
this.D.T(this.player,"onShowControls",function(){b.oa("onShowControls")});
this.D.T(this.player,"resize",function(d){b.oa("resize",d)});
this.D.T(this.player,"presentingplayerstatechange",function(d){b.oa("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.O0,this);this.subscribe("resize",this.lJ,this);this.player.U().Na.subscribe("vast_info_card_add",this.HY,this);g.L(this,this.events);this.qa=this.createElement({I:"div",S:"video-custom-annotations"});this.B=new g.U({I:"div",Ma:["ytp-player-content","ytp-iv-player-content"]});g.L(this,this.B);g.qU(this.player,this.B.element,4);this.B.hide();this.C=new g.U({I:"div",Ma:["ytp-iv-video-content"]});g.L(this,this.C);a=this.createElement({I:"div",S:"video-annotations"});
a.appendChild(this.qa);this.C.element.appendChild(a);this.au()&&this.load();var c=this.createElement({I:"style"});(g.Qe("HEAD")[0]||document.body).appendChild(c);g.ub(this,function(){g.rf(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Qjb=function(a){a=a.createElement({I:"div",
Ma:["annotation","annotation-type-custom"]});g.Pr(a,!1);return a},Rjb=function(a,b){b=!b.isCued()&&!g.VG(b,1024);
g.mG(a.B,b);g.mG(a.C,b)},Sjb=function(a,b,c){a.N=!0;
a.G=g.gC(b,c)},Tjb=function(a,b){for(var c={},d=g.u(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.$a(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Tjb(a,e))}return c},Xjb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.U().Na.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.aC(h)&&h.responseXML?h.responseXML:null)&&Ujb(a,h)}};
g.nD()&&(d.onFinish=Vjb(a,d.onFinish));d.postParams={ic_only:"1"};Wjb(d,c);a.N=!0;g.gC(b.Ta,d)}}},Wjb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.KG&&(a.postParams.ic_coll=b.KG);b.sM&&(a.postParams.ic_xml=b.sM);b.zK&&(a.postParams.ic_track=b.zK)},Yjb=function(a){var b=new g.U({I:"div"});
g.Pr(b.element,!1);var c=new njb(a.player,b.element,B4(a));g.L(c,b);b.Ea(a.B.element);c.xF();return c},$jb=function(a,b){var c,d;
if(b=null==(c=b.Hd)?void 0:null==(d=c.cards)?void 0:d.cardCollectionRenderer)a.Y=!0,Zjb(a,b),b.headerText&&a.uh&&(c=g.qG(b.headerText),a.uh.setAttribute("title",c))},B4=function(a){if(!a.Z){var b=new Hib(a);
g.L(a,b);var c=new g.wo(a);g.L(a,c);a.Z=new Hjb(b,c,a.player.U(),a.player.getVideoData(),a.logger,a.player,a.lj)}return a.Z},Ujb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.KF();if(e){var f=g.JF();f&&g.OB(g.nua)(void 0,e,f,[g.IF(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Tjb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=i4(f.type,akb),p=i4(f.style,bkb),q=Xib(f.data),r=0!==q.length?JSON.parse(q):{};var t=f.action;f=cjb;if(null==t)var v=null;else if(g.Za(t)){l=[];for(var x=g.u(t),C=x.next();!C.done;C=x.next()){var G=f(C.value);
G&&l.push(G)}v=l}else{var F=f(t);v=F?[F]:[]}e=m&&n?new djb(m,n,p,v,r):null}else e=null}catch(ta){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=Qjb(f),O=null;switch(l.type){case "branding":if(f.player.U().Ld)break;f.B.element.appendChild(I);O=new z4(I,B4(f),l);break;case "promotion":g.qU(f.player,I,4),O=new Ijb(I,B4(f),l)}O&&O.xF();if(f=O)g.L(a,f),a.K[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Yjb(a),g.L(a,a.j));if("card"===e.type){c=a.j;var Q=e&&e.data&&e.data.card_type;
f=e.data;if(Q)switch(l=f.tracking||{},l={PW:l.impression,click:l.click,close:l.close,e_:l.teaser_impression,vK:l.teaser_click},I=f.tracking_params||{},O=null,Q){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.IF(I.card):null,Al:I.teaser?g.IF(I.teaser):null,og:I.icon?g.IF(I.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,cZ:f.image_url,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.IF(I.card):null,Al:I.teaser?
g.IF(I.teaser):null,og:I.icon?g.IF(I.icon):null,IF:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "productListing":f.signin_url&&(O=k4({target:"current",value:f.signin_url}));Q=[];for(var Y=f.offers||[],ia=0;ia<Y.length;ia++)Q.push(new jjb(g.Be(Y[ia].merchant),g.Be(Y[ia].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.IF(I.card):null,Al:I.teaser?g.IF(I.teaser):null,og:I.icon?g.IF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,tC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),bhb:O,ahb:f.signin_title?f.signin_title:void 0,Zgb:f.signin_message?f.signin_message:void 0,offers:Q,onClickCommand:null};t4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.IF(I.card):
null,Al:I.teaser?g.IF(I.teaser):null,og:I.icon?g.IF(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,tC:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};t4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,bj:l,So:I.card?g.IF(I.card):null,Al:I.teaser?g.IF(I.teaser):null,og:I.icon?g.IF(I.icon):null,IF:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:k4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},t4(c,e)}}else ojb(a.j,e);c=!0}}c&&
(U3(a.player),a.lJ())},Zjb=function(a,b){var c=!1;
a.j||(a.j=Yjb(a),g.L(a,a.j));for(var d=g.u(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(pjb(a.j,e.cardRenderer),c=!0);if(c){var f;null!=(f=a.player.getVideoData())&&g.KT(f)||(c=a.j,d=b.headerText?g.qG(b.headerText):"",g.Df(c.Qb,d),c.Z&&c.Z.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Da=b.trackingParams?g.IF(b.trackingParams):null,c.N=b.closeButton.infoCardIconRenderer.trackingParams?g.IF(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.og=b.icon.infoCardIconRenderer.trackingParams?g.IF(b.icon.infoCardIconRenderer.trackingParams):null,a.lJ());U3(a.player)}},ckb=function(a,b,c,d,e){if(!a.player.U().Ld){var f=[];
b.navigationEndpoint&&g.S(b.navigationEndpoint,g.QU)&&g.S(b.navigationEndpoint,g.QU).browseId&&f.push(new $ib("openUrl","click",new Yib("/channel/"+g.S(b.navigationEndpoint,g.QU).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.S(b.subscribeButton,
g.DT)){d.channel_id=g.S(b.subscribeButton,g.DT).channelId;var l;b=g.S(b.subscribeButton,g.DT);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.qG(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.qG(b.subscriberCountText))):(b.subscriberCountText&&(e=g.qG(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.qG(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.S(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.L2))?void 0:m.url)||"";l={subscribeText:g.qG(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.qG(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new djb(c,"branding","branding",f,d);l=Qjb(a);a.B.element.appendChild(l);f=new z4(l,B4(a),f);f.xF();g.L(f,f);a.K[c]=f}},Vjb=function(a,b){return function(){var c=g.Ja.apply(0,arguments);
a.isDisposed()||a.ma.push(g.Xt.Li(function(){b.apply(null,g.oa(c))}))}},dkb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.iU.prototype.YA=g.ca(19,function(a,b){var c=g.OV(this.Eb());c&&c.YA(a,b)});
var W3={},X3=null;g.kb(Z3,g.Au);g.k=Z3.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.B;else if(this.isPlaying())return!1;Y3(this);this.startTime=a=g.ib();this.isPaused()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.cJ();this.Yl("play");this.isPaused()&&this.Yl("resume");this.j=1;var b=g.cb(this);b in W3||(W3[b]=this);Aib();Bib(this,a);return!0};
g.k.stop=function(a){Y3(this);this.j=0;a&&(this.progress=1);Cib(this,this.progress);this.Yl("stop");this.lr()};
g.k.pause=function(){this.isPlaying()&&(Y3(this),this.j=-1,this.Yl("pause"))};
g.k.ya=function(){0==this.j||this.stop(!1);this.Yl("destroy");Z3.Of.ya.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.UK=function(){this.Yl("animate")};
g.k.Yl=function(a){this.dispatchEvent(new Dib(a,this))};
g.kb(Dib,g.xb);g.kb($3,Z3);$3.prototype.C=function(){};
$3.prototype.UK=function(){this.C();$3.Of.UK.call(this)};
$3.prototype.lr=function(){this.C();$3.Of.lr.call(this)};
$3.prototype.cJ=function(){this.C();$3.Of.cJ.call(this)};
g.kb(Eib,$3);Eib.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.w(Hib,g.J);g.k=Hib.prototype;g.k.Sa=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=g.PC(a,b,c);this.j.push(a);return a};
g.k.zI=function(a,b,c,d){c=(0,g.fb)(c,d||this.B);a=yib(a,b,c);this.j.push(a);return a};
g.k.Pc=function(a){g.QC(a);g.Gb(this.j,a)};
g.k.Lf=function(){g.QC(this.j);this.j.length=0};
g.k.ya=function(){this.Lf();g.J.prototype.ya.call(this)};g.w(Kib,g.xV);g.k=Kib.prototype;g.k.load=function(){g.xV.prototype.load.call(this);if(!c4(this)){var a=g.rRa(this.player.getVideoData());a?(a=Jib(a,Lib(this)),d4(this,a,!1)):Mib(this)}};
g.k.unload=function(){d4(this,null);this.C&&(this.C.abort(),this.C=null);g.xV.prototype.unload.call(this)};
g.k.Jh=function(a,b){return c4(this)?"loadCustomEndscreenRenderer"===a?(a=Jib(b,"new"),d4(this,a),!0):null:null};
g.k.getOptions=function(){return c4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Lb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<ekb.length;f++){var h=Math.abs(b.width-ekb[f]);if(-1===e||d>=h)e=f,d=h}d=fkb[e];this.B&&g.Dr(this.B.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.G[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Nr(e.element,m,f);g.Jr(e.element,n,p);g.pu(e.element,gkb);256<m||256<f?g.mu(e.element,"ytp-ce-large-round"):96<m||96<f?g.mu(e.element,"ytp-ce-medium-round"):g.mu(e.element,"ytp-ce-small-round");g.pu(e.element,hkb);m=h.left+h.width/2;h=h.top+l/2;g.mu(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.pu(e.element,fkb);g.mu(e.element,d);(e=g.Re(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Dr(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())h4(this,this.endscreen.impressionUrls),(a=g.KF())&&this.endscreen.visualElement&&g.YF(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.G[a];g.mu(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.mu(b,"ytp-ce-shown");h4(this,c.impressionUrls);(b=g.KF())&&g.YF(b,c.visualElement);this.player.U().K&&this.player.Ra("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.ou(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.ou(b,"ytp-ce-shown");this.player.U().K&&this.player.Ra("endscreenelementhidden",a)}};
g.k.Q9=function(a){var b=this;a.target===window&&(new g.eu(function(){for(var c=g.u(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.pu(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var ekb=[346,426,470,506,570,640,853,1280,1920],fkb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),hkb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],gkb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Zib={Fqa:"current",zQa:"new"};var ajb={CLOSE:"close",aUa:"openUrl",SUBSCRIBE:"subscribe"},bjb={hpa:"click",CLOSE:"close",aCa:"hidden",aZa:"rollOut",bZa:"rollOver",H_a:"shown"};djb.prototype.bf=function(){var a=ejb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var bkb={bka:"anchored",m0:"branding",CHANNEL:"channel",vqa:"cta",dCa:"highlightText",eGa:"label",PLAYLIST:"playlist",yWa:"popup",E2a:"speech",SUBSCRIBE:"subscribe",S5a:"title",VIDEO:"video",fcb:"website"},akb={m0:"branding",ana:"card",Isa:"drawer",cCa:"highlight",gMa:"marker",VXa:"promotion",TEXT:"text",Gdb:"widget"};g.w(o4,g.J);g.k=o4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.iK(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.fb.set(a,e);this.context.J.tf([a])};
g.k.xF=function(){this.context.B.subscribe("resize",this.FG,this)};
g.k.Db=function(){return this.element};
g.k.VK=function(a,b,c,d,e,f){if(this.wb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.rf(this.Db())};
g.k.FG=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=j4(a);if(f){var h=ljb(f,a.target),l=function(){a.j&&e.context.J.pauseVideo();var m=e.context.videoData.Qd||!1,n=g.UB(f||"");m&&n&&(n.v||n.list)?e.context.J.xo(n.v,b,n.list,!1):g.oH(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);A4(this.context.logger,c,l,d);kjb(f)||(c=g.KF(),d=b.itct,c&&d&&g.aG(c,g.IF(d)))}};
g.k.ya=function(){this.Za.clear();this.fb.clear();g.J.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.w(njb,o4);g.k=njb.prototype;g.k.kt=function(){this.qa&&t4(this,this.qa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.J.getRootNode())?(a=g.Or(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.FG=function(){var a=this.isAvailable();g.Pr(this.Db(),a);g.qu(this.context.J.getRootNode(),g.bZ.IV_DRAWER_ENABLED,a);U3(this.J)};
g.k.destroy=function(){this.J.YA(!1);try{this.J.getRootNode().removeChild(this.D)}catch(a){}g.OE(this.ma);g.VC(this.Ta);this.Va&&this.Va.dispose();this.G&&this.G.dispose();o4.prototype.destroy.call(this)};
g.k.j4=function(){if(this.C){A4(this.context.logger,x4(this).bj.close);var a=g.KF();a&&this.N&&g.aG(a,this.N);s4(this)}};
g.k.D4=function(){g.qu(this.D,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.k.E6=function(){var a=g.KF(),b=x4(this);b=b?b.og:this.og;a&&b&&g.ZF(a,[b])};
g.k.D6=function(){var a=g.KF(),b=x4(this);b=b?b.og:this.og;a&&b&&g.$F(a,[b])};
g.k.N0=function(){var a=x4(this);A4(this.context.logger,a.bj.e_);var b=g.KF();b&&a&&g.ZF(b,[a.Al,a.og])};
g.k.F6=function(){var a=g.KF(),b=x4(this);a&&b&&g.$F(a,[b.Al])};
g.k.M0=function(a){var b=x4(this),c=g.KF();this.j?a?(a=this.context.logger,A4(a,b.bj.vK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.Al&&g.aG(c,b.Al)):(a=this.context.logger,A4(a,b.bj.vK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&b.og&&g.aG(c,b.og)):(a=this.context.logger,A4(a,b.bj.vK),a.J.sendVideoStatsEngageEvent(4,void 0),c&&this.og&&g.aG(c,this.og))};g.w(y4,o4);y4.prototype.xF=function(){o4.prototype.xF.call(this);Cjb(this)};
y4.prototype.show=function(){o4.prototype.show.call(this);var a=g.KF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.ZF(a,[g.IF(b.itct)])};
y4.prototype.hide=function(){o4.prototype.hide.call(this);var a=g.KF(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.$F(a,[g.IF(b.itct)])};g.w(z4,y4);z4.prototype.Qw=function(){g.mu(this.Db(),"iv-branding");var a=this.annotation.data;this.B=this.createElement({I:"img",Ma:["branding-img","iv-click-target"],W:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Pr(this.B,!1);var b=this.createElement({I:"button",Ma:["branding-img-container","ytp-button"]});b.appendChild(this.B);this.Db().appendChild(b);var c=this.annotation.bf();c&&p4(this,b,c,this.annotation.id,a.session_data);Gjb(this,a)};
z4.prototype.show=function(){if(!this.isActive&&(y4.prototype.show.call(this),this.N||(this.Qw(),this.N=!0),g.Pr(this.Db(),!0),this.isActive=!0,this.B)){try{Djb(this,this.B)}catch(a){}g.mu(this.context.J.getRootNode(),"ytp-branding-shown")}};
z4.prototype.hide=function(){this.isActive&&(y4.prototype.hide.call(this),g.Pr(this.Db(),!1),this.isActive=!1,g.ou(this.context.J.getRootNode(),"ytp-branding-shown"))};
z4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);y4.prototype.destroy.call(this)};g.w(Ijb,y4);g.k=Ijb.prototype;
g.k.Qw=function(){var a=this,b=this.annotation.data;if("cta"===this.annotation.style)var c=6;else if("video"===this.annotation.style||"playlist"===this.annotation.style)c=7;this.K=b.collapsedelay_ms||this.K;var d=["iv-promo","iv-promo-inactive"];this.Db().setAttribute("aria-hidden","true");this.Db().setAttribute("aria-label","Promotion");this.Db().tabIndex=0;var e=this.annotation.bf(),f=b.image_url;if(f){var h=this.createElement({I:"div",Ma:["iv-promo-img","iv-click-target"]});f=this.createElement({I:"img",
W:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&!b.is_live?(f=this.createElement({I:"span",S:"iv-promo-video-duration",xa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=this.createElement({I:"span",S:"iv-promo-playlist-length",xa:b.playlist_length.toString()}),h.appendChild(f));e&&p4(this,h,e,this.annotation.id,b.session_data,void 0,c)}e?(f=this.createElement({I:"a",S:"iv-promo-txt"}),g.Hn(f,j4(e)),this.j=f):this.j=this.createElement({I:"div",S:"iv-promo-txt"});switch(this.annotation.style){case "cta":case "website":var l=
this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_1}]});var m=this.createElement({I:"p",V:[{I:"span",S:"iv-promo-link",xa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=this.createElement({I:"button",Ma:["iv-promo-round-expand-icon","ytp-button"]});f=this.createElement({I:"button",Ma:["iv-button","iv-promo-button"],V:[{I:"span",S:"iv-button-content",xa:f}]});var p=this.createElement({I:"div",S:"iv-promo-button-container"});p.appendChild(f);e&&p4(this,
this.Db(),e,this.annotation.id,b.session_data,void 0,c)}g.mu(this.j,"iv-click-target");e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=this.createElement({I:"p",V:[{I:"span",xa:b.text_line_1}]}),m=this.createElement({I:"p",V:[{I:"strong",xa:b.text_line_2}]}),b.is_live&&(l=m,m=this.createElement({I:"span",Ma:["yt-badge","iv-promo-badge-live"],xa:"LIVE NOW"})),g.mu(this.j,"iv-click-target"),e&&p4(this,this.j,e,this.annotation.id,b.session_data,void 0,
c),d.push("iv-promo-video")}l&&this.j.appendChild(l);m&&this.j.appendChild(m);this.N.appendChild(this.j);p&&this.N.appendChild(p);c=this.createElement({I:"div",S:"iv-promo-actions"});this.B=this.createElement({I:"button",Ma:["iv-promo-expand","ytp-button"]});this.B.title="Expand";this.context.j.Sa(this.B,"click",function(q){Ljb(a,5E3,q)});
c.appendChild(this.B);g.Pr(this.B,!1);this.context.j.Sa(this.Db(),"mouseover",this.F5,this);this.context.j.Sa(this.Db(),"mouseout",this.E5,this);this.context.j.Sa(this.Db(),"touchend",function(q){Ljb(a,5E3,q)});
this.C=this.createElement({I:"button",Ma:["iv-promo-close","ytp-button"]});this.C.title="Close";this.context.j.Sa(this.C,"click","cta"===this.annotation.style&&b.text_line_3?this.A5:this.z5,this);c.appendChild(this.C);g.nu(this.Db(),d);h&&(g.of(this.Db(),h),n&&h.appendChild(n));g.of(this.Db(),this.N);g.of(this.Db(),c)};
g.k.show=function(){this.isActive||(y4.prototype.show.call(this),this.Y||(this.Qw(),this.Y=!0),g.Pr(this.Db(),!0),g.fg(function(){g.ou(this.Db(),"iv-promo-inactive")},100,this),this.Db().removeAttribute("aria-hidden"),this.isActive=!0,Njb(this),Jjb(this),Kjb(this,this.K))};
g.k.hide=function(){this.isActive&&(g.mu(this.Db(),"iv-promo-inactive"),this.isActive=!1,this.Db().setAttribute("aria-hidden","true"))};
g.k.VK=function(a,b,c,d,e,f){return this.isCollapsed?!1:y4.prototype.VK.call(this,a,b,c,d,e,f)};
g.k.F5=function(a){this.Z=!0;Ljb(this,500,a)};
g.k.E5=function(){this.Z=!1;Mjb(this)};
g.k.z5=function(a){a.stopPropagation();this.hide()};
g.k.A5=function(a){a.stopPropagation();Njb(this);this.isCollapsed=!0;g.mu(this.Db(),"iv-promo-collapsed-no-delay");this.G.start()};
g.k.destroy=function(){this.G.dispose();y4.prototype.destroy.call(this)};g.w(Pjb,g.xV);g.k=Pjb.prototype;g.k.Jh=function(a,b){if(!dkb(this.player.U().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.q2(b))&&Ujb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&(rjb(this.j,b),U3(this.player)),!0}return null};
g.k.getOptions=function(){return dkb(this.player.U().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.au=function(){var a=this.player.U(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.Qd&&a.ma||g.gU(this.player.app)?!1:1===c&&!b.oU||a.Na.get(b.videoId)||g.LT(b)||g.sRa(b)?!0:!1};
g.k.lJ=function(){if(this.C){var a=this.player.qb().getVideoContentRect(!0);g.Nr(this.C.element,a.width,a.height);g.Jr(this.C.element,a.left,a.top)}if(this.j){var b=this.player.Qk();a=this.j;b=b.width;g.qu(a.D,"iv-drawer-small",426>=b);g.qu(a.D,"iv-drawer-big",1280<=b)}};
g.k.O0=function(a){Rjb(this,a.state);g.VG(a.state,2)&&(this.Fk()&&this.Ro()&&2!==this.player.getPresentingPlayerType()&&this.ZA(!1),this.YA(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.aC(h)&&h.responseXML?h.responseXML:null)&&(Ujb(b,h),g.mu(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.xV.prototype.load.call(this);Rjb(this,this.player.Tb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.nD()&&(a=Vjb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.U().Na.get(d);f&&Wjb(e,f);f=f&&(f.sM||f.KG);if(!c.Du||f)c.Ta?Sjb(this,c.Ta,e):(this.ox=function(){if(!b.N)b.onVideoDataChange(e);var h=b.player.getVideoData();(null==h?0:g.KT(h))&&!b.Y&&$jb(b,h)},this.player.addEventListener("videodatachange",this.ox));
g.qU(this.player,this.C.element,4);this.lJ();(f=g.LT(c))&&Zjb(this,f);(f=g.sRa(c))&&f.featuredChannel&&ckb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null);this.uh=g.Ze("ytp-cards-button",this.player.getRootNode());g.KT(c)&&$jb(this,c)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Sjb(this,b.Ta,a)};
g.k.unload=function(){this.player.hf("annotations_module");for(var a=g.u(Object.keys(this.K)),b=a.next();!b.done;b=a.next())this.K[b.value].destroy();this.Z=null;this.j&&(this.j.destroy(),this.j=null,U3(this.player));this.N=!1;this.G&&(this.G.abort(),this.G=null);this.Y=!1;this.K={};this.B.hide();g.xV.prototype.unload.call(this);this.C.detach();this.ox&&(this.player.removeEventListener("videodatachange",this.ox),this.ox=null)};
g.k.HY=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Xjb(this):this.load())};
g.k.Fk=function(){var a;return(null==(a=this.j)?void 0:a.isAvailable())||this.Y};
g.k.Ro=function(){return!!this.j&&this.j.C};
g.k.ZA=function(a,b,c){b=void 0===b?!1:b;this.Fk();this.j&&(a?c?r4(this.j,c,b):r4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):s4(this.j))};
g.k.YA=function(a,b){this.player.oa(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ya=function(){this.player.U().Na.unsubscribe("vast_info_card_add",this.HY,this);g.ou(this.player.getRootNode(),g.bZ.IV_DRAWER_OPEN);for(var a=this.ma,b=g.Xt,c=0,d=a.length;c<d;c++)b.Lj(a[c]);this.ma.length=0;g.xV.prototype.ya.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.L(this,a);return a.element};g.wV("annotations_module",Pjb);g.wV("creatorendscreen",Kib);})(_yt_player);
